### PR TITLE
Add articulation map for Shreddage 3 guitars

### PR DESCRIPTION
**Pull request by vanceism7**
I created articulation mapping for shreddage 3. I tried to approximate as close as possible to the standardized mapping described on reaticulate.com.

Let me know if anything needs changing/fixing!

### CODE REVIEW

**Comment by jtackaberry** [comment]
Really sorry about the long delay @vanceism7.  The bank is functional although it would be nice if icon and color attributes were included.

It's not a showstopper -- if you're willing to do it (or perhaps by now you've already done it), I'll hold off before merging.  Otherwise, something is of course quite a lot better than nothing. :)

**Comment by vanceism7** [comment]
Ah no, I haven't done it yet lol, mainly just due to laziness and I was in a music writing flow at the time lol.

I just read the guide on the colors and icons; it doesn't seem too hard so I'll see if I can get those finished up this weekend!

**Comment by vanceism7** [comment]
Ok, icons and colors have been added to the shreddage 3 articulations!

**Comment by jtackaberry** [comment]
Better very late than never. Thanks @vanceism7

**Pull request merged**
