### PR TITLE
 Add Peteris Vasks Strings user reabank 

### PR DESCRIPTION
**Pull request by steamwings**
Most of the work was done by the creator(s) of [OTR](https://www.orchestraltemplateforreaper.com/) (extracted from OTR/Data/otr-orchestral-tools.reabank), but I did a little editing. Mainly, I added reaticulate icons (before they were all left as list).

(Sorry for creating another PR; I didn't see a way that GitHub allowed changing branches from the forked repo after #209 was created.)

### CODE REVIEW

**Comment by jtackaberry** [comment]
I've been meaning to trawl through Jonathan's herculean OTR work at some point to see what was liftable. 

The channel mappings that are baked into these banks, is this specific to OTR track templates for this library (where the articulations are assigned to different channels in a custom way), or is it how the VI works out of the box?   I'm basically wondering if these banks are of general use to non-OTR users.

**Comment by steamwings** [comment]
> I've been meaning to trawl through Jonathan's herculean OTR work at some point to see what was liftable.
> 
> The channel mappings that are baked into these banks, is this specific to OTR track templates for this library (where the articulations are assigned to different channels in a custom way), or is it how the VI works out of the box? I'm basically wondering if these banks are of general use to non-OTR users.

Yeah, these mappings are for Orchestral Tools' SINE Player's default settings. I'm not using OTR (although it looks like it has a ton of great stuff in it).

**Comment by jtackaberry** [comment]
Sorry for the shockingly long turnaround on this one.  There are some small tweaks needed (lots of `o=@<n>` redundancies that can be removed), but I'll take care of that after merging.

Thanks!

**Comment by jtackaberry** [comment]
Adjusted the group (`g`) and patch name (`n`) attributes to be more consistent with other OT userbanks in the collection.

Also fixed a typo in the Finger Tremolo min3 articulation in the Celli patch where the MIDI channel was wrong.  (`o=@2/cc@2:3,1/note@24,127` was changed to `o=cc@2:3,1/note@2:24,127`)

**Pull request merged**
