### PR TITLE
Add banks for EastWest Hollywood Opus

### PR DESCRIPTION
**Pull request by xshill**
I created some user banks for the EastWest Hollywood Opus edition keyswitches. The ones we already had in the repo were for the Play engine, and the keyswitch instruments that come with the Opus engine are different.

### CODE REVIEW

**Comment by gbombadil** [comment]
From what I could check my version has all available articulations while his has only the ones that came with the default Keyswitch instrument. Thats true at least for Woodwinds.
MyVersion
HisVersion

**Comment by jtackaberry** [comment]
@xshill can you confirm?  Is #212 a superset of your PR?  I don't have this library so there may be considerations I'm not aware of.

Thanks!

**Comment by gbombadil** [comment]
Hello, just checking, how much time of waiting is appropiate in this cases? 

Thanks in advance....

**Comment by GrizzlyAK** [comment]
Does anyone know if the EW Strings and Percussion have been added by anyone for the OPUS edition?

**Comment by xshill** [comment]
> @xshill can you confirm? Is #212 a superset of your PR? I don't have this library so there may be considerations I'm not aware of.
> 
> Thanks!

Holy crap, I'm so sorry about the late reply; Github never notified me or anything and I completely forgot to check back on this PR.

I took a quick look and it does indeed look like it implements more articulations that mine does (I only did the default articulations for keyswitch instruments, as mentioned).

Thanks @gbombadil !

**Comment by jtackaberry** [comment]
Very slow for the inexcusably slow turnaround time on this one.  I've renamed the top-level group from EastWest to EastWest Quantum Leap so it's consistent with other EWQL userbanks in the collection.

And I've included @gbombadil's Woodwinds banks from #212, with some minor adjustments there so the patch naming is more consistent across the collection.

**Pull request merged**
