### PR TITLE
Add Orchestral Tools Clutch reabank

### PR DESCRIPTION
**Pull request by steamwings**
Add reabank for another free OT VST

### CODE REVIEW

**Comment by jtackaberry** [comment]
The UUID is a little suspect, looks like it was from Peteris Vasks Strings - Violins I with the first two digits changed.

We should use a properly random one here.  Can you remove the id attribute and let Reaticulate generate a new one?  Alternatively, you could use https://www.uuidgenerator.net/version4

**Comment by steamwings** [comment]
> The UUID is a little suspect, looks like it was from Peteris Vasks Strings - Violins I with the first two digits changed.
> 
> We should use a properly random one here. Can you remove the id attribute and let Reaticulate generate a new one? Alternatively, you could use https://www.uuidgenerator.net/version4

That's almost certainly what I did lol. Good catch

**Comment by steamwings** [comment]
This was updated in [39638bb](https://github.com/jtackaberry/reaticulate/pull/214/commits/39638bbb1602cb6dbcdb01250de2460ebde7f0b3). Let me know if there are other changes needed

**Comment by jtackaberry** [comment]
> Let me know if there are other changes needed

There are, but I've let this PR languish for so long that it's not fair for me to ask now :)  I'll merge and take care of the necessary changes.

Thanks @steamwings!

**Pull request merged**
